{
 "title": "Substrate Networking",
 "description": "Information related to the networking layer of Substrate",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "nodename",
    "label": "Instance name filter",
    "query": "${metric_namespace}_process_start_time_seconds"
   },
   {
    "name": "notif_protocol",
    "query": "${metric_namespace}_sub_libp2p_notifications_sizes_count{instance=~\"${nodename}\"}"
   },
   {
    "name": "request_protocol",
    "query": "${metric_namespace}_sub_libp2p_requests_in_success_total_count{instance=~\"${nodename}\"}"
   },
   { "name": "data_source", "label": "Source of data", "query": "prometheus" },
   { "name": "metric_namespace", "label": "Prefix of the metrics", "query": "${VAR_METRIC_NAMESPACE}" }
  ]
 },
 "panels": [
  { "title": "$nodename", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }, "repeat": "nodename" },
  { "title": "Transport", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Average transport-level (TCP, QUIC, ...) connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"in\", instance=~\"${nodename}\"}) by (instance) -\n  sum(${metric_namespace}_sub_libp2p_connections_closed_total{direction=\"in\", instance=~\"${nodename}\"}) by (instance)\n)\n\n# Because `closed_total` can be null, this serves as fallback\nor on(instance) sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"in\", instance=~\"${nodename}\"}) by (instance)",
     "legendFormat": "established (in)"
    },
    {
     "expr": "(\n  sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"out\", instance=~\"${nodename}\"}) by (instance) -\n  sum(${metric_namespace}_sub_libp2p_connections_closed_total{direction=\"out\", instance=~\"${nodename}\"}) by (instance)\n)\n\n# Because `closed_total` can be null, this serves as fallback\nor on(instance) sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"out\", instance=~\"${nodename}\"}) by (instance)",
     "legendFormat": "established (out)"
    },
    {
     "expr": "sum by (instance) (${metric_namespace}_sub_libp2p_pending_connections{instance=~\"${nodename}\"})",
     "legendFormat": "pending (out)"
    },
    {
     "expr": "sum(rate(${metric_namespace}_sub_libp2p_connections_closed_total{instance=~\"${nodename}\"}[$__interval]))",
     "legendFormat": "closed-per-sec"
    }
   ]
  },
  {
   "title": "Percentage of peers for which we have more than one connection open",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - \n\navg(\n  ${metric_namespace}_sub_libp2p_distinct_peers_connections_opened_total{instance=~\"${nodename}\"} - ${metric_namespace}_sub_libp2p_distinct_peers_connections_closed_total{instance=~\"${nodename}\"}\n) by (instance)\n\n/\n\navg(\r\n  sum(${metric_namespace}_sub_libp2p_connections_opened_total{instance=~\"${nodename}\"}) by (instance) - sum(${metric_namespace}_sub_libp2p_connections_closed_total{instance=~\"${nodename}\"}) by (instance)\r\n) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of incoming connection errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_incoming_connections_handshake_errors_total{instance=~\"${nodename}\"}[$__interval])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_listeners_errors_total{instance=~\"${nodename}\"}[$__interval])",
     "legendFormat": "pre-handshake"
    }
   ]
  },
  {
   "title": "Network bandwidth - # bytes per second",
   "type": "graph",
   "description": "Each bucket represent a certain number of nodes using a certain bandwidth range.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_network_bytes_total{instance=~\"${nodename}\"}[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Dialing attempt errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_pending_connections_errors_total{instance=~\"${nodename}\"}[$__interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Disconnects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short", "label": "Disconnects" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_connections_closed_total{instance=~\"${nodename}\"}[$__interval])",
     "legendFormat": "{{reason}} ({{direction}})"
    }
   ]
  },
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Number of peer slots filled",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "${metric_namespace}_sub_libp2p_peerset_num_requested{instance=~\"${nodename}\"}",
     "legendFormat": "peers-requested"
    },
    {
     "expr": "polkadot_sub_libp2p_peers_count{instance=~\"${nodename}.*\"}",
     "legendFormat": "peers-count"
    }
   ]
  },
  { "title": "Requests (${request_protocol})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }, "repeat": "request_protocol" },
  {
   "title": "Requests emitted per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 47 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(${metric_namespace}_sub_libp2p_requests_out_success_total_sum{instance=~\"${nodename}\", protocol=\"${request_protocol}\"}[5m]) + on(instance) sum(irate(${metric_namespace}_sub_libp2p_requests_out_failure_total{instance=~\"${nodename}\", protocol=\"${request_protocol}\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outbound requests failures",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 51 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(${metric_namespace}_sub_libp2p_requests_out_failure_total{instance=~\"${nodename}\", protocol=\"${request_protocol}\"}[$__rate_interval])) by (instance, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Median request answer time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 55 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(${metric_namespace}_sub_libp2p_requests_out_success_total_bucket{instance=~\"${nodename}\", protocol=\"${request_protocol}\"}[5m])) by (instance, le)) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99th percentile request answer time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 59 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(${metric_namespace}_sub_libp2p_requests_out_success_total_bucket{instance=~\"${nodename}\", protocol=\"${request_protocol}\"}[5m])) by (instance, le)) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests served per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 63 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(${metric_namespace}_sub_libp2p_requests_in_success_total_count{instance=~\"${nodename}\", protocol=\"${request_protocol}\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inbound requests failures",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 67 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(${metric_namespace}_sub_libp2p_requests_in_failure_total{instance=~\"${nodename}\", protocol=\"${request_protocol}\"}[$__rate_interval])) by (instance, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Median request serving time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 71 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(${metric_namespace}_sub_libp2p_requests_in_success_total_bucket{instance=~\"${nodename}\", protocol=\"${request_protocol}\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99th percentile request serving time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 75 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(${metric_namespace}_sub_libp2p_requests_in_success_total_bucket{instance=~\"${nodename}\", protocol=\"${request_protocol}\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Notifications (${notif_protocol})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "repeat": "notif_protocol"
  },
  {
   "title": "Number of open substreams",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${metric_namespace}_sub_libp2p_notifications_streams_opened_total{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"} - ${metric_namespace}_sub_libp2p_notifications_streams_closed_total{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average network notifications per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "cps", "label": "Notifs/sec" }
   ],
   "targets": [
    {
     "expr": "avg by (direction) (irate(${metric_namespace}_sub_libp2p_notifications_sizes_count{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[$__rate_interval]))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Average bandwidth used by notifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "Bps", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "expr": "avg(irate(${metric_namespace}_sub_libp2p_notifications_sizes_sum{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Total sizes of notifications waiting to be delivered to the rest of Substrate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(${metric_namespace}_sub_libp2p_out_events_notifications_sizes{instance=~\"${nodename}\", protocol=\"${notif_protocol}\", action=\"sent\"} - ignoring(action) ${metric_namespace}_sub_libp2p_out_events_notifications_sizes{instance=~\"${nodename}\", protocol=\"${notif_protocol}\", action=\"received\"}) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average size of sent and received notifications in the past 5 minutes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 104 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "bytes", "label": "Max. notification size" }
   ],
   "targets": [
    {
     "expr": "sum(rate(${metric_namespace}_sub_libp2p_notifications_sizes_sum{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[5m])) by (direction, protocol) / sum(rate(${metric_namespace}_sub_libp2p_notifications_sizes_count{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[5m])) by (direction, protocol)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Maximum size of sent and received notifications in the past 5 minutes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 110 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "bytes", "label": "Max. notification size" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(${metric_namespace}_sub_libp2p_notifications_sizes_bucket{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[5m])) by (direction, le))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "99th percentile of queues sizes",
   "type": "graph",
   "description": "99.9% of the time, the output queue size for this protocol is below the given value",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 116 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(${metric_namespace}_sub_libp2p_notifications_queues_size_bucket{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[2m])) by (le, instance))",
     "legendFormat": "{{protocol}}"
    },
    {
     "expr": "max(histogram_quantile(0.99, sum(rate(${metric_namespace}_sub_libp2p_notifications_queues_size_bucket{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[2m])) by (le, instance)))",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "GrandPa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "GrandPa messages received from the network, and action",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 123 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_finality_grandpa_communication_gossip_validator_messages{instance=~\"${nodename}\"}[$__interval])",
     "legendFormat": "{{message}} => {{action}}"
    }
   ]
  },
  { "title": "Kademlia & authority-discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Kademlia and Authority Discovery metrics moved to \"kademlia-and-authority-discovery\" dashboard.",
   "type": "dashlist",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 }
  }
 ]
}