global:
  scrape_interval: 15s
scrape_configs:
  - job_name: plug-nodes
    static_configs:
      - targets: ['alice:9615']
        labels:
          network: local
      - targets: ['bob:9615']
        labels:
          network: local
      - targets: ['charlie:9615']
        labels:
          network: local
