name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.maintain/**'
      - 'docs/**'
      - '.dockerignore'
      - '.editorconfig'
      - '.git*'
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.maintain/**'
      - 'docs/**'
      - '.dockerignore'
      - '.editorconfig'
      - '.git*'
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        rustup install $VERSION_NIGHTLY
        rustup install $VERSION_STABLE
        rustup default $VERSION_STABLE
        rustup target add --toolchain=$VERSION_NIGHTLY wasm32-unknown-unknown
        #rustup target add --toolchain=$VERSION_STABLE  x86_64-unknown-linux-musl
      env:
        VERSION_STABLE: 1.44.1
        VERSION_NIGHTLY: nightly-2020-04-17
    - name: Check
      run: cargo check
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --workspace
